//
// Created by 张一鸣 on 2017/1/8.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_LIST_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_LIST_H

void polynomials_test_list();

#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_LIST_H
