//
// Created by 张一鸣 on 2017/1/7.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_H

void polynomials_test();

#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_POLYNOMIALS_H
