//
// Created by 张一鸣 on 2017/1/9.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTSTKA_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTSTKA_H
int testStka( );
#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTSTKA_H
