//
// Created by 张一鸣 on 2017/1/13.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTHASH_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTHASH_H
int testhash( );
#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTHASH_H
