//
// Created by 张一鸣 on 2017/1/19.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTLEFTHEAP_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTLEFTHEAP_H

void testleftheap();

#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTLEFTHEAP_H
