//
// Created by 张一鸣 on 2017/1/10.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTQUEUE_H
#define DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTQUEUE_H
int testqueue( );
#endif //DATA_STRUCTURES_AND_ALGORITHM_ANALYSIS_IN_C_TESTQUEUE_H
